### ISSUE TITLE
Concerning fix

### ISSUE THREAD

**Issue by DanNBullock** [DanNBullock/OCT_scripts#11]
https://github.com/DanNBullock/OCT_scripts/blob/2484479c27b25642a9d87e253b5f8ceca7edef7d/computeIndexRangeForElipsoidEccDegree.m#L80

I worry that with this we are letting the tail wag the dog.  Outside of this function, the code understands that we are on some specific angle, but here we are correcting it due to the rounding error incurred by indexing.  

Maybe the proper way to do this is the other way around, and to select the pixels that correspond to the adjusted radius (i.e. computing the adjustment before selecting the voxels).  other wise, we end up selecting y axis pixels for angle 11  or 12, and outputting them with x axis pixels for 9 or 10.

**Comment by JasleenKJolly** [comment]
I am wondering whether if we include an interpolation step we can get rid of all this complex maths. If we interpolate the data in between the measurement points then when we draw the circle we don't need to worry about how coarse of fine the data is?

**Comment by DanNBullock** [comment]
No longer used
