### ISSUE TITLE
replace this line with a variable input, for transparency and modifiable purposes

### ISSUE THREAD

**Issue by DanNBullock** [DanNBullock/OCT_scripts#17]
https://github.com/DanNBullock/OCT_scripts/blob/39ad178ca99775eab98bd33f0e4f7310c5f9d521/MAIAcode/computeMAIAgroupMeansDegrees.m#L45

it would be up at the top of the function specification.  It would be a cell array of integer sequences, i.e. {2:5,6:17... etc}

**Comment by JasleenKJolly** [comment]
I think this is sensible as it makes it usuable for a variety of microperimetry plots.

**Comment by DanNBullock** [comment]
done 
https://github.com/DanNBullock/OCT_scripts/commit/d4cc7fd121d725eeeb8c26e17feb7af64499f100
