### ISSUE TITLE
.gitsubmodule should not use git@ URL

### ISSUE THREAD

**Issue by soichih** [DanNBullock/OCT_scripts#22]
app-maiaRings App is failing to start because it uses this repo as submodule which then uses nifti_tools as its own submodule with the URL of

```
[submodule "nifti_tools"]
	path = nifti_tools
	url = git@github.com:francopestilli/nifti_tools.git
```

This should be updated to 

```
[submodule "nifti_tools"]
	path = nifti_tools
	url = https://github.com/francopestilli/nifti_tools.git
```

git@ URL requires ssh key to access, and none of brainlife's user is equipped with its own ssh key to access it.

**Comment by DanNBullock** [comment]
updated both this repo and app repo

https://github.com/DanNBullock/OCT_scripts/commit/2d8db91a78bf234b368ee1a82207c189c26dd01c

https://github.com/brainlife/app-maiaRings/commit/0a0eda590d5cad08d36753641450ef233a690a9b

**Comment by jkjolly** [comment]
Thank you 😊
