### ISSUE TITLE
Ping Jasleen about this

### ISSUE THREAD

**Issue by DanNBullock** [DanNBullock/OCT_scripts#5]
https://github.com/DanNBullock/OCT_scripts/blob/2484479c27b25642a9d87e253b5f8ceca7edef7d/computeIndexRangeForElipsoidEccDegree.m#L62

**Comment by JasleenKJolly** [comment]
I am wondering whether if we include an interpolation step we can get rid of all this complex maths. If we interpolate the data in between the measurement points then when we draw the circle we don't need to worry about how coarse of fine the data is?

**Comment by DanNBullock** [comment]
So in essence interpolate the input array such that the x and y dimensions
are the same?  I've thought about doing that with this (
https://www.mathworks.com/help/images/ref/imresize.html) but I was worried
that this might somehow mess up the math of computing the mean.  Its
probably fine though, and will make things a great deal easier.

**Comment by JasleenKJolly** [comment]
This looks like a good solution.. I think this will make the border problem easier to deal with making things more accurate.

**Comment by DanNBullock** [comment]
Dimensions are now interpolated to isometry
