### ISSUE TITLE
Sanity check

### ISSUE THREAD

**Issue by DanNBullock** [DanNBullock/OCT_scripts#6]
https://github.com/DanNBullock/OCT_scripts/blob/2484479c27b25642a9d87e253b5f8ceca7edef7d/computeIndexRangeForElipsoidEccDegree.m#L93

This seemed to trigger every time on angle 10.  Check what's going on.

**Comment by JasleenKJolly** [comment]
That is coming up to the upper limit of the scans so there are likely lots of border effects in the data.

**Comment by DanNBullock** [comment]
No longer used
