### ISSUE TITLE
Impliment fractional check here too?

### ISSUE THREAD

**Issue by DanNBullock** [DanNBullock/OCT_scripts#7]
https://github.com/DanNBullock/OCT_scripts/blob/2484479c27b25642a9d87e253b5f8ceca7edef7d/elipsoidMaskFromRangeIndexes.m#L56

If we have the fractional check elsewhere, do we need it here too?

**Comment by JasleenKJolly** [comment]
Depends where the other check is? As you are now making this modular, is the check in the same module?

**Comment by DanNBullock** [comment]
No longer used
